### ISSUE TITLE
Creating a mobile app

### ISSUE THREAD

**Issue by staminna** [dreamerkumar/bizsitegenie#3]
Hi dreamerKumar,

What kind of solution is best about how to get this stack running "natively" in mobile devices?
I Need to get it into the Apple Store and Play Store there seems to be a catch with Cordova.
Here is a thread about this in https://forum.ionicframework.com/t/using-ionic-with-mean-js-full-stack/5052/2 where gnomeontherun states Apple may reject this. I quote 

> Move your ionic www/ directory into the app/ directory of your mean.js project. Then you have to create a standalone cordova project, and point the app to use load assets from your mean.js server using . I don't recommend this, and have heard doing this may cause Apple to reject your app (because you can change the content of the app without going through their approval chain).
> 
> Cordova, Ionic, and AngularJS are what you build your mobile app with. MongoDB runs on a server, which is not going to be in your mobile app. You need something that is known as a RESTful service layer, which allows you to load data from a url into the mobile app, but it runs and stores data on a server somewhere else. Consider this tutorial http://scotch.io/tutorials/javascript/build-a-restful-api-using-node-and-express-4

What are your thoughts on this?
Have a great weekend

**Comment by dreamerkumar** [comment]
Let me read up on the links and get back to you.

**Comment by staminna** [comment]
That's ok.  I quoted the most important parts. Do you think I need to get a Restful API to go around the issue?

**Comment by dreamerkumar** [comment]
All the data is pulled through restful apis. You don't need new restful apis for sure. But you will need to do some repackaging of the Front End files. Instead of node server returning the default index.html file, it will now have to be packaged in your mobile app. 

I am not sure what is the specific issue you are talking about?

**Comment by staminna** [comment]
The stack is new to me. Just wanted to know if you were familiar releasing on App/Play Store. 

Should I be creating a symbolic link between /website and cordova/www and edit the static index.html as provided with the Cordova project and make it look like bizsitegenie including the .js and .css files?

Have a great weekend
Jorge

**Comment by staminna** [comment]
I created a symbolic link between the public and Ionic's www docroot and matched the paths for required libraries except that there is a problem.

![screenshot 2016-10-22 21 03 15](https://cloud.githubusercontent.com/assets/515180/19622159/034a2666-989b-11e6-9ba5-6dbaaa90c291.png)

Quote from the Angular documentation:

> Error: ng:areq
> Bad Argument
> Argument 'BaseController' is not a function, got undefined
> 
> Description
> AngularJS often asserts that certain values will be present and truthy using a helper function. If the assertion fails, this error is thrown. To fix this problem, make sure that the value the assertion expects is defined and matches the type mentioned in the error.

Here is the static index.html.
http://pastebin.com/E0jwuhyV

**Comment by staminna** [comment]
Fixed broken link with static index.html file above.
Do you get an email update every time I edit the post? please let me know, that would explain a lot. I am always trying to improve the question

**Comment by dreamerkumar** [comment]
Nope. Not for the edits

**Comment by staminna** [comment]
Thanks dreamerkumar. I may have edited the previous post since you got the notification 4 days ago about the symbolic links. Moving on, I have both servers running at the same time. The issue is now 

> Argument 'BaseController' is not a function, got undefined.

The only occurrence in the index.html file of BaseController is in the main body tag.

`<body ng-app="starter" class="ng-cloak" data-ng-controller="BaseController" ng-class="{'home-background': !isAuthenticated|| buildRoleDoesNotExist}">
`

I think figuring this out would be the last issue on this thread.
What do you think about this?

**Comment by dreamerkumar** [comment]
I would think this has to do with missing or incorrect file reference. I
would try to look through and find how the source file for basecontroller
is included. And see whether it is part of the packaged set of files for
your mobile app and if the path is correct.

**Comment by staminna** [comment]
Actually BaseController is defined in bizsitegenie side and It's now being loaded.

It can be found in application.js file and base.client.controller.js
I added this sources to the main <header> tag before the <body> call, but the error message is still the same.

``````
<!-- your app's js -->
    <script src="js/app.js"></script>
    <script src="public/modules/core/controllers/base.client.controller.js"></script>
    <script src="public/dist/application.js"></script>```

Inside js/app.js there is some code provided by the Ionic's blank boilerplate with curious code.

`// Ionic Starter App

// angular.module is a global place for creating, registering and retrieving Angular modules
// 'starter' is the name of this angular module example (also set in a <body> attribute in index.html)
// the 2nd parameter is an array of 'requires'
angular.module('starter', ['ionic'])

.run(function($ionicPlatform) {
  $ionicPlatform.ready(function() {
    if(window.cordova && window.cordova.plugins.Keyboard) {
      // Hide the accessory bar by default (remove this to show the accessory bar above the keyboard
      // for form inputs)
      cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);

      // Don't remove this line unless you know what you are doing. It stops the viewport
      // from snapping when text inputs are focused. Ionic handles this internally for
      // a much nicer keyboard experience.
      cordova.plugins.Keyboard.disableScroll(true);
    }
    if(window.StatusBar) {
      StatusBar.styleDefault();
    }
  });
})
`

Do you think this may have to do with the angular.module(..) stuff in the app.js file? Thanks for this. I will PM you soon with what I am trying to achieve.
``````

**Comment by dreamerkumar** [comment]
I didn't realize you had to use ionic specifc angular code. From the code above, it looks like starter is the base module that is bootstrapped into the html. I am not sure how exactly it is all tying together. But maybe adding the module for basecontroller as a dependency next to ionic might work.

**Comment by staminna** [comment]
I will try to use a webview inside Ionic and see if I can get approved in Apple/Play store.
