### ISSUE TITLE
datepicker option and css override

### ISSUE THREAD

**Issue by staminna** [dreamerkumar/bizsitegenie#4]
Hi Dreamerkumar

I am looking for where to set javascript options array for internationalization of the widget.
[http://bootstrap-datepicker.readthedocs.io/en/latest/i18n.html](url)

Basically, I need to set 

> `$.fn.datepicker.dates['en'] = {
    days: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
    daysShort: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    daysMin: ["Su", "Mo", "Tu", "We", "Th", "Fr", "Sa"],
    months: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
    monthsShort: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    today: "Today",
    clear: "Clear",
    format: "mm/dd/yyyy",
    titleFormat: "MM yyyy", /* Leverages same syntax as 'format' */
    weekStart: 0
};`

Thanks

**Comment by dreamerkumar** [comment]
Not sure on this one Staminna.

**Comment by staminna** [comment]
I created a issue to the datepicker package maintainers. Will report back when I know more

**Comment by staminna** [comment]
To do this, you need to import the locale.js file to the template for the language you need and set moment.locale('pt'); to set for Portuguese for example.
