### ISSUE TITLE
Dynamically add image/attachments properties in the client side.

### ISSUE THREAD

**Issue by staminna** [dreamerkumar/bizsitegenie#6]
Hey dreamerkumar.

I need to show a button to "add another image" when someone uploads a image to attachment into the image / file properties for multiple file support. Which files should I be looking at?

Thanks

**Comment by dreamerkumar** [comment]
You should make the change in the template html file for the item to which you have added the attachment property. Look in the website/public/modules/[youritemname]/views/ folder

**Comment by staminna** [comment]
Thanks, I think I should be able to do this now

**Comment by staminna** [comment]
I shouldn't have closed the issue. 
If I am required to generate new forms again, these files will be regenerated, thus overwritten, right?
Also requires .js code as well as html. I can see both  builder/app/controllers/public/modules/item/views/create-item.client.view.html public/modules/item/views/create-item.client.view.html 
are equal and also I am struggling with angular on this. Here is a [Plunker](http://plnkr.co/edit/n4BKHFWG0HnmhZ4rBjG5?p=preview) example.

**Comment by dreamerkumar** [comment]
Yes. The files do get regenerated and any previous changes will be reset.
That's a limitation of this system at this time.
