### ISSUE TITLE
User and Groups permissions

### ISSUE THREAD

**Issue by staminna** [dreamerkumar/bizsitegenie#7]
Hi

Something changed when I try to update updating the files with new properties. Changes are not committed to hard disk. New properties are not becoming available.

![screenshot 2016-11-10 16 21 29](https://cloud.githubusercontent.com/assets/515180/20184930/34630fbc-a762-11e6-9cd4-aea29f3211d3.png)

I am certain I haven't changed any permissions in the file system.

**Comment by dreamerkumar** [comment]
So it is saying that the operation was a success when actually it failed. This seems like a bug. One way to get the actual error would be to run the command to generate files directly from the command prompt.

**Comment by dreamerkumar** [comment]
Before that, can you look for this file in your folder structure and see what the logged error is:
generatefeatures_results.log

**Comment by dreamerkumar** [comment]
website/builder/app/controllers/generatefeatures.sh has the commands that are run to generate the files. You can run that directly from the website folder to achieve the same thing. Replace the $1 with your app id. It's easy to find the app id from the url of your application.

**Comment by dreamerkumar** [comment]
app id is also in the screenshot that you have provided.

**Comment by staminna** [comment]
Had to install mocha with npm, and fixed a little typo on a template and it works. Thanks!

**Comment by staminna** [comment]
```
$ ./builder/app/controllers/generatefeatures.sh 
running command yo builder:crud-from-db with parameter 

Native thread-sleep not available.
This will result in much slower performance, but it will still work.
You should re-install spawn-sync or upgrade to the lastest version of node if possible.
Check /usr/local/lib/node_modules/yo/node_modules/spawn-sync/error.log for more details

Error: Cannot find module 'underscore.inflections'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/jorge/webapp/project/AdvGest/generator-builder/crud-from-json-file/crudModulePlusCaller.js:3:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
Running "jshint:all" (jshint) task

   public/modules/adiantamento/adiantamento.client.module.js
      1 |'use strict';
         ^ Use the function form of "use strict".
      4 |ApplicationConfiguration.registerModule('adiantamento');
         ^ 'ApplicationConfiguration' is not defined.
   public/modules/adiantamento/config/adiantamento.client.routes.js
      1 |'use strict';
         ^ Use the function form of "use strict".
      4 |angular.module('adiantamento').config(['$stateProvider',
         ^ 'angular' is not defined.
   public/modules/adiantamento/controllers/adiantamento.client.controller.js
      1 |'use strict';
         ^ Use the function form of "use strict".
    142 |                        console.error('Error occurred on getting adiantamento', err)
                                                                                             ^ Missing semicolon.
    177 |                        console.error('Error occurred on getting adiantamento', err)
                                                                                             ^ Missing semicolon.
      4 |angular.module('adiantamento').controller('AdiantamentoController', ['$scope', '$stateParams', '$location', 'Authentication', 'Authorization', 'Adiantamento',
         ^ 'angular' is not defined.
    142 |                        console.error('Error occurred on getting adiantamento', err)
                                 ^ 'console' is not defined.
    177 |                        console.error('Error occurred on getting adiantamento', err)
                                 ^ 'console' is not defined.
   public/modules/adiantamento/services/adiantamento.client.service.js
      1 |'use strict';
         ^ Use the function form of "use strict".

```
These files were automatically generated by bizsitegenie and I can't find anything else on my end. yo doctor says it's all good. The errors are hundreds, even with multiple different node versions and as per the installation videos. >> 1786 errors in 212 files

> node -v
> 0.10.45
> 4.7.2
> 5.0.2
> 6.0.1
> 

property Updated -> Resource doesn't show on console anymore.
generateItems shows in grey text. 
I also tried to install underscore.inflections on different paths but I couldn't find the right one anywhere.
Can you help?

**Comment by staminna** [comment]
I have two clientes, each with different roles and permissions, but both can read and write from each other. Is it that angular is not creating the colours in the browser as I explained in the post above?
