### ISSUE TITLE
https support

### ISSUE THREAD

**Issue by staminna** [dreamerkumar/bizsitegenie#8]
Hi

I created a SSL certificate and replaced port 443 to 8443 in the code to get past the initial issues and run 

> $ NODE_ENV=secure node server.js
> 
> Securely using https protocol
> MEAN.JS application started on port 8443

but not all required files are being loaded properly. Here is the call stack 

![ng-cookies](https://cloud.githubusercontent.com/assets/515180/20319564/8a1dfcfc-ab66-11e6-815e-26cdca93a7be.png)

and here is the HTML generated
![screenshot 2016-11-15 19 06 39](https://cloud.githubusercontent.com/assets/515180/20319591/ab3a5f20-ab66-11e6-9690-b228e75d7a7d.png)

thanks

**Comment by dreamerkumar** [comment]
I didn't get a chance to test secure. Please see if all config entries (in the configs folder) for secure match up to the corresponding ones for production.

**Comment by staminna** [comment]
That was easy. Some files were missing
Thank you :)
